# Database Connection
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: liquibase
  liquibase:
    url: jdbc:postgresql://localhost/postgres
    driverClassName: org.postgresql.Driver
    user: postgres
    password: liquibase
    changeLog: "classpath:db/changelog/main-changelog.yml"
    contexts: prod
    dropFirst: false

logging.level.org.springframework.data.r2dbc: DEBUG